graph LR
  user(["👤 SubSeer User"])
  manager(["👤 Household Manager"])
  member(["👤 Household Member"])


  subgraph SubSeer Menu

    UC1((Login/Logout/Signup))

    UC2((Create/Remove/Join Households))

  end


  user --> UC1
  user --> UC2

  manager --> user
  member --> user

  subgraph SubSeer Households

    UC3((Remove Subscriptions))

    UC4((View Household Join Code))

    UC5((Access Subscription Information))

    UC6((Add Subscriptions))

  end

    manager --> UC3
    manager --> UC4
    manager --> UC5
    manager --> UC6

    member --> UC5
    member --> UC6



    


